### ISSUE TITLE
Data not pulled from Omnifocus

### ISSUE THREAD

**Issue by seancrookston** [rhydlewis/omnifocus-to-kanban#2]
Everything is now configured right, but when I run the script it doesn't post any cards. What is the criteria for an Omnifocus Task being Brough up?

**Comment by seancrookston** [comment]
This is what I get when I run the command 

Traceback (most recent call last):
  File "./bin/of-to-kb", line 70, in <module>
    main()
  File "./bin/of-to-kb", line 42, in main
    external_ids = board.find_completed_card_ids()
  File "./kanban/kanban_board.py", line 25, in find_completed_card_ids
    card_ids = self.board.cards_with_external_ids(lanes)
  File "./kanban/leankit/board.py", line 167, in cards_with_external_ids
    if len(card.external_card_id) > 1]) for lane in lanes]
TypeError: 'int' object is not iterable

**Comment by seancrookston** [comment]
user error
